name: Deploy the application to Google Cloud Run
on:
  push:
    branches:
    - Rotfuks-patch-1
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GKE_SECRET: ${{ secrets.GCLOUD_AUTH_BASE64 }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: us-west1-a
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  IMAGE: shopsafe-server
  REGISTRY_HOSTNAME: gcr.io
  DEPLOYMENT_NAME: gke-test
  BACKEND_WORKING_DIRECTORY: ./backend

jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      # Setup JDK  
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11
        # Gradle Build
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: $BACKEND_WORKING_DIRECTORY
      - name: Build with Gradle
        run: "./gradlew build"
        working-directory: $BACKEND_WORKING_DIRECTORY
     - name: Docker
        run: "docker build -t "$REGISTRY_HOSTNAME"/"$GKE_PROJECT"/"$IMAGE":"$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg JAR_FILE=build/libs/*.jar ."
        working-directory: ${{ env.BACKEND_WORKING_DIRECTORY }} 
      - name: Authenticate into Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
      - name: Configure Docker to use Google Cloud Platform
        run: "gcloud auth configure-docker"